### ISSUE TITLE
Improvement suggestion for delays

### ISSUE THREAD

**Issue by halfguru** [AstroCoding/btd6_autoplay#4]
Hi guys,

Good job guys on the improvements, appreciate the new modular and extensible architecture! I have a small suggestion for the tower placement and upgrades delays. Determining how many seconds we need to wait is rather tedious for someone to check. Additionally, if I check the `moveToRest` function, time wait is not accurate because click and press actions are performed every "second" too. Instead, I would add a functionality for round and specific current tower upgrade detection. For example, when doing `dart.upgrade('/', 2)` , you would wait indefinitely inside a loop until the upgrade is available (which can be easily differentiated with the green and grey background). As for tower placement, I'd wait until a particular round is reached to place it.

The advantage of proceeding this way is a user only needs to add rounds for placement/upgrades in  `settings.json`. This makes it  much more user friendly.

**Comment by AstroCoding** [comment]
We attempted to implement these suggestions, but the libraries we used for image parsing were just horribly unreliable for this idea. We may come back to this down the line, but until this day, we are going to be keeping the current structure.

**Comment by halfguru** [comment]
No problem. Good luck with your project!

**Comment by AstroCoding** [comment]
@halfguru Hey, don't know if you remember this project, but with the latest updates to Pytesseract, we decided to implement your suggestion. Should definitely make lives a lot easier.

**Comment by halfguru** [comment]
@AstroCoding Awesome! Will check it out 👍
